[[tests]]
name = "1"
input = ["./$project", "O", "?", "O", "X", "?", "X", "?", "?", "?"]
expected = """
O | ? | O
--+---+--
X | ? | X
--+---+--
? | ? | ?
O: 0 1
"""
rubric = 10

[[tests]]
name = "2"
input = ["./$project", "O", "?", "X", "X", "O", "?", "?", "?", "?"]
expected = """
O | ? | X
--+---+--
X | O | ?
--+---+--
? | ? | ?
O: 2 2
"""
rubric = 10
